const dogs_pt = {
  affenpinscher: "Affenpinscher",
  african: "Cão-selvagem-africano",
  airedale: "Airedale Terrier",
  akita: "Akita Inu",
  appenzeller: "Boiadeiro de Appenzell",
  australian_shepherd: "Pastor Australiano",
  basenji: "Basenji",
  beagle: "Beagle",
  bluetick: "Bluetick Coonhound",
  borzoi: "Borzoi",
  bouvier: "Boiadeiro de Flandres",
  boxer: "Boxer",
  brabancon: "Petit Brabançon",
  briard: "Pastor de Brie",
  buhund_norwegian: "Buhund Norueguês",
  bulldog_boston: "Boston Terrier",
  bulldog_english: "Bulldog Inglês",
  bulldog_french: "Bulldog Francês",
  bullterrier_staffordshire: "Bull Terrier",
  cattledog_australian: "Boiadeiro Australiano",
  chihuahua: "Chihuahua",
  chow: "Chow Chow",
  clumber: "Clumber Spaniel",
  cockapoo: "Cockapoo",
  collie_border: "Border Collie",
  coonhound: "Coonhound Preto e Castanho",
  corgi_cardigan: "Welsh Corgi Cardigan",
  cotondetulear: "Coton de Tulear",
  dachshund: "Salsicha",
  dalmatian: "Dálmata",
  dane_great: "Dogue Alemão",
  deerhound_scottish: "Deerhound Escocês",
  dhole: "Cão-selvagem-asiático",
  dingo: "Cão-selvagem-australiano",
  doberman: "Doberman",
  elkhound_norwegian: "Elkhound Norueguês Cinza",
  entlebucher: "Boiadeiro de Entlebuch",
  eskimo: "Cão Esquimó Canadense",
  finnish_lapphund: "Cão-finlandês-da-lapônia",
  frise_bichon: "Bichon Frisé",
  germanshepherd: "Pastor Alemão",
  greyhound_italian: "Galgo Italiano",
  groenendael: "Pastor Belga Groenendael",
  havanese: "Bichon Havanês",
  hound_afghan: "Galgo Afegão",
  hound_basset: "Bassê",
  hound_blood: "Bloodhound",
  hound_english: "Foxhound inglês",
  hound_ibizan: "Podengo Ibicenco",
  hound_plott: "Plott Hound",
  hound_walker: "Treeing Walker Coonhound",
  husky: "Husky Siberiano",
  keeshond: "Wolfspitz",
  kelpie: "Kelpie Australiano",
  komondor: "Komondor",
  kuvasz: "Kuvasz",
  labradoodle: "Labradoodle",
  labrador: "Labrador",
  leonberg: "Leonberger",
  lhasa: "Lhasa Apso",
  malamute: "Malamute do Alasca",
  malinois: "Pastor Belga Malinois",
  maltese: "Maltês",
  mastiff_bull: "Bullmastiff",
  mastiff_english: "Mastiff Inglês",
  mastiff_tibetan: "Mastim Tibetano",
  mexicanhairless: "Pelado Mexicano",
  mix: "Vira-lata",
  mountain_bernese: "Boiadeiro Bernês",
  mountain_swiss: "Grande Boiadeiro Suíço",
  newfoundland: "Terra-nova",
  otterhound: "Otterhound",
  ovcharka_caucasian: "Pastor do Cáucaso",
  papillon: "Papillon",
  pekinese: "Pequinês",
  pembroke: "Welsh Corgi Pembroke",
  pinscher_miniature: "Pinscher",
  pitbull: "Pitbull",
  pointer_german: "Braco Alemão de Pelo Curto",
  pointer_germanlonghair: "Braco Alemão de Pelo Longo",
  pomeranian: "Lulu da pomerânia",
  poodle_medium: "Poodle Médio",
  poodle_miniature: "Poodle Anão",
  poodle_standard: "Poodle Gigante",
  poodle_toy: "Poodle Toy",
  pug: "Pug",
  puggle: "Puggle",
  pyrenees: "Cão de montanha dos Pirenéus",
  redbone: "Redbone Coonhound",
  retriever_chesapeake: "Retriever da Baía de Chesapeake",
  retriever_curly: "Retriever de Pelo Encaracolado",
  retriever_flatcoated: "Retriever de Pelo Liso",
  retriever_golden: "Golden Retriever",
  ridgeback_rhodesian: "Rhodesian Ridgeback",
  rottweiler: "Rottweiler",
  saluki: "Saluki",
  samoyed: "Samoieda",
  schipperke: "Schipperke",
  schnauzer_giant: "Schnauzer Gigante",
  schnauzer_miniature: "Schnauzer Anão",
  segugio_italian: "Segugio Italiano",
  setter_english: "Setter Inglês",
  setter_gordon: "Setter Gordon",
  setter_irish: "Setter Irlandês",
  sharpei: "Shar Pei",
  sheepdog_english: "Sheepdog",
  sheepdog_shetland: "Pastor de Shetland",
  shiba: "Shiba Inu",
  shihtzu: "Shih Tzu",
  spaniel_blenheim: "Cavalier King Charles Spaniel",
  spaniel_brittany: "Spaniel Bretão",
  spaniel_cocker: "Cocker Spaniel Inglês",
  spaniel_irish: "Spaniel D'água Irlandês",
  spaniel_japanese: "Chin",
  spaniel_sussex: "Sussex Spaniel",
  spaniel_welsh: "Springer Spaniel Galês",
  spitz_japanese: "Spitz Japonês",
  springer_english: "Springer Spaniel Inglês",
  stbernard: "St. Bernard",
  terrier_american: "American Pit Bull Terrier",
  terrier_australian: "Terrier Australiano",
  terrier_bedlington: "Bedlington Terrier",
  terrier_border: "Border Terrier",
  terrier_cairn: "Cairn Terrier",
  terrier_dandie: "Dandie Dinmont Terrier",
  terrier_fox: "Fox Terrier",
  terrier_irish: "Terrier Irlandês",
  terrier_kerryblue: "Terrier Kerry Blue",
  terrier_lakeland: "Terrier Lakeland",
  terrier_norfolk: "Terrier Norfolk",
  terrier_norwich: "Terrier Norwich",
  terrier_patterdale: "Terrier Patterdale",
  terrier_russell: "Jack Russell Terrier",
  terrier_scottish: "Terrier Escocês",
  terrier_sealyham: "Terrier Sealyham",
  terrier_silky: "Terrier Silky",
  terrier_tibetan: "Terrier Tibetano",
  terrier_toy: "Toy Fox Terrier",
  terrier_welsh: "Welsh Terrier",
  terrier_westhighland: "West Highland White Terrier",
  terrier_wheaten: "Soft Coated Wheaten Terrier",
  terrier_yorkshire: "Yorkshire",
  tervuren: "Pastor Belga Tervuren",
  vizsla: "Vizsla",
  waterdog_spanish: "Cão D'Água Espanhol",
  weimaraner: "Weimaraner",
  whippet: "Whippet",
  wolfhound_irish: "Wolfhound Irlandês",
} as any;

export default dogs_pt;
